# Generated by Django 5.2.17 on 2026-09-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregado el'),
        ),
        migrations.CreateModel(
            name='OrderStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Hito / etapa')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada')], default='pendiente', max_length=16, verbose_name='Estado')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas de entrega',
                'ordering': ['created_at'],
            },
        ),
    ]
