# Generated by Django 5.2.17 on 2026-09-06 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_delivery_terms_tenant_giro_tenant_warranty'),
        ('orders', '0002_f2_entregas_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Abonado parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=16, verbose_name='Estado de cobro'),
        ),
        migrations.CreateModel(
            name='DeliveryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre de la plantilla')),
                ('stages', models.JSONField(blank=True, default=list, verbose_name='Etapas')),
                ('is_system', models.BooleanField(default=False, verbose_name='Sugerida por Nexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_templates', to='core.tenant', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Plantilla de etapas',
                'verbose_name_plural': 'Plantillas de etapas',
                'ordering': ['-is_system', 'name', 'id'],
            },
        ),
    ]
