# Generated by Django 5.2.17 on 2026-09-06 05:02

import apps.quotations.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, verbose_name='Folio')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('vista', 'Vista'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida')], default='borrador', max_length=16, verbose_name='Estado')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de emisión')),
                ('valid_until', models.DateField(default=apps.quotations.models._default_valid_until, verbose_name='Válida hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Condiciones / notas')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento')),
                ('subtotal_net', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Subtotal neto')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Total')),
                ('approval_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='clients.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Cantidad')),
                ('unit_price_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Precio unitario neto')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dto. %')),
                ('iva_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='IVA (%)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('tenant', 'folio'), name='unique_tenant_quotation_folio'),
        ),
    ]
