# Generated by Django 5.2.17 on 2026-09-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(blank=True, default='Pago inmediato / transferencia', max_length=140, verbose_name='Forma de pago'),
        ),
    ]
