# Generated by Django 5.2.17 on 2026-09-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='approval_comment',
            field=models.TextField(blank=True, default='', verbose_name='Comentario del cliente'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo del aprobador'),
        ),
        migrations.CreateModel(
            name='QuotationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creada', 'Creada'), ('enviada', 'Enviada'), ('vista', 'Vista'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida')], max_length=16, verbose_name='Acción')),
                ('by_name', models.CharField(blank=True, default='', max_length=120)),
                ('by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quotations.quotation', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Historial',
                'ordering': ['-created_at'],
            },
        ),
    ]
