# Generated by Django 5.2.17 on 2026-09-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='delivery_terms',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Plazo de entrega'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='giro',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Garantía'),
        ),
    ]
