# Generated by Django 5.2.17 on 2026-09-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_delivery_terms_tenant_giro_tenant_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'Sistema'), ('light', 'Claro'), ('dark', 'Oscuro')], default='system', max_length=8, verbose_name='Tema'),
        ),
    ]
