/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "../templates/**/*.html",
    "../apps/**/*.html",
    "../apps/**/*.py",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed-dim": "#4edea3",
        "on-surface-variant": "#464555",
        "primary-fixed": "#e2dfff",
        secondary: "#855300",
        "on-surface": "#131b2e",
        background: "#faf8ff",
        "on-primary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-secondary-container": "#684000",
        tertiary: "#005338",
        "on-error": "#ffffff",
        "surface-container": "#eaedff",
        primary: "#3525cd",
        "inverse-on-surface": "#eef0ff",
        "on-secondary-fixed-variant": "#653e00",
        surface: "#faf8ff",
        "on-error-container": "#93000a",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb95f",
        "on-tertiary-container": "#67f4b7",
        "on-secondary-fixed": "#2a1700",
        "primary-container": "#4f46e5",
        "surface-container-high": "#e2e7ff",
        "secondary-container": "#fea619",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-container": "#006e4b",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#dae2fd",
        "inverse-surface": "#283044",
        "secondary-fixed": "#ffddb8",
        "surface-container-low": "#f2f3ff",
        outline: "#777587",
        "surface-dim": "#d2d9f4",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "on-primary-fixed": "#0f0069",
        "inverse-primary": "#c3c0ff",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf8ff",
        "surface-tint": "#4d44e3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.5rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "gutter-desktop": "1.5rem",
        "container-max": "76rem",
        "space-xxs": "0.25rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "600" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "76rem",
      },
    },
  },
  plugins: [],
};