# Generated by Django 5.2.17 on 2026-09-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, verbose_name='Folio')),
                ('name', models.CharField(max_length=160, verbose_name='Nombre / Razón social')),
                ('rut', models.CharField(blank=True, default='', max_length=20, verbose_name='RUT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
