# Generated by Django 5.2.17 on 2026-09-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='giro',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Giro'),
        ),
    ]
