# Generated by Django 5.2.17 on 2026-09-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_tenant_delivery_terms_tenant_giro_tenant_warranty'),
        ('quotations', '0003_f2_entregas_aprobacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vista', 'Cotización vista'), ('aprobada', 'Cotización aprobada'), ('rechazada', 'Cotización rechazada'), ('por_vencer', 'Cotización por vencer')], max_length=16, verbose_name='Categoría')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='Destino')),
                ('threshold', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Umbral (días)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quotations.quotation', verbose_name='Cotización')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'category', 'quotation', 'threshold'), name='unique_tenant_user_category_quote_threshold')],
            },
        ),
    ]
